"use strict";
exports.__esModule = true;
var express_1 = require("express");
var body_parser_1 = require("body-parser");
var Auth_1 = require("../Middlewares/Auth");
var authentication_1 = require("../Controllers/authentication");
var addUser_1 = require("../Controllers/addUser/addUser");
var addLocal_1 = require("../Controllers/addLocal");
var rateLocalById_1 = require("../Controllers/rateLocalById");
var rateLocalByName_1 = require("../Controllers/rateLocalByName");
var getLocalsByList_1 = require("../Controllers/getLocalsByList");
var getLocalsByMap_1 = require("../Controllers/getLocalsByMap");
var getLocalRates_1 = require("../Controllers/getLocalRates");
var getUserPerfil_1 = require("../Controllers/getUserPerfil");
var changeUserPassword_1 = require("../Controllers/changeUserPassword");
var changeUserEmail_1 = require("../Controllers/changeUserEmail");
var logout_1 = require("../Controllers/logout");
var updateUserPerfil_1 = require("../Controllers/updateUserPerfil");
var swagger_ui_express_1 = require("swagger-ui-express");
var swaggerFile = require("../api-spec.json");
var app = express_1["default"]();
app.use(body_parser_1.json());
function routes() {
    app.use('/api/docs', swagger_ui_express_1.serve, swagger_ui_express_1.setup(swaggerFile));
    app.get("/api/v1/getLocalsByList", Auth_1["default"], getLocalsByList_1["default"]);
    app.get("/api/v1/getLocalsByMap/:lat/:lng", Auth_1["default"], getLocalsByMap_1["default"]);
    app.get("/api/v1/getLocalRates/:id", Auth_1["default"], getLocalRates_1["default"]);
    app.get("/api/v1/getUserPerfil", Auth_1["default"], getUserPerfil_1["default"]);
    app.get("/api/v1/logout", Auth_1["default"], logout_1["default"]);
    app.post("/api/v1/addLocal", Auth_1["default"], addLocal_1["default"]);
    app.post("/api/v1/user", Auth_1["default"], addUser_1["default"]);
    app.post("/api/v1/authenticate", authentication_1["default"]);
    app.post("/api/v1/rateLocalById", Auth_1["default"], rateLocalById_1["default"]);
    app.post("/api/v1/rateLocalByName", Auth_1["default"], rateLocalByName_1["default"]);
    app.patch("/api/v1/changeUserPassword", Auth_1["default"], changeUserPassword_1["default"]);
    app.patch("/api/v1/changeUserEmail", Auth_1["default"], changeUserEmail_1["default"]);
    app.put("/api/v1/updateUserPerfil", Auth_1["default"], updateUserPerfil_1["default"]);
    app.listen(process.env.PORT || 3001);
}
exports["default"] = routes;
